steps:
  - label: "Sentence"
    key: "Sentence"
    plugins:
      - docker#v5.12.0:
          image: python:3.13
          mount-buildkite-agent: true
          user: root
    command: |
      pip install .
      python -c "from loremipsum import sentence; print(sentence(max_char=20))" > result.txt
      buildkite-agent annotate --style "success" --context "sentence" "$(cat result.txt)"

  # - label: "Annotate"
  #   command: |
  #     buildkite-agent artifact download result.txt .
  #     buildkite-agent annotate --style "success" --context "sentence" "$(cat result.txt)"
  #   depends_on: "Sentence"
  - label: "Paragraph"
    key: "Paragraph"
    plugins:
      - docker#v5.12.0:
          image: python:3.13
          mount-buildkite-agent: true
          user: root
    command: |
      pip install .
      python -c "from loremipsum import paragraph; print(paragraph(max_char=100))" > result2.txt
      buildkite-agent annotate --style "success" --context "paragraph" "$(cat result2.txt)"
      buildkite-agent artifact upload "result2.txt"
    depends_on: "Sentence"
  # - label: "Artifact"
  #   command: |
  #     buildkite-agent artifact upload "result2.txt"
  #   depends_on: "Paragraph"
  - label: "Print"
    command: |
      buildkite-agent artifact download "result2.txt" .
      cat result2.txt
    depends_on: "Paragraph"
    